### ISSUE TITLE
Unable to change baseurl

### ISSUE THREAD

**Issue by usuallymatt** [treetrum/amazon-kindle-bulk-downloader#107]
I'm trying to use this with amazon.ca when I run the program it logs me in no issue to the Australian site. If I run using this command:
npm run start  -- --baseURL=https://www.amazon.ca

the script reports:
ts-node src/index.ts --baseURL=https://www.amazon.ca

but it still goes to the Australian site. I've also tried: npm run start --baseURL=https://www.amazon.ca
but still it goes to the Australian site. How should I be wording the command to go to amazon.ca?

Thanks

**Comment by treetrum** [comment]
Hey there, can you try passing the arg like this:

`npm run start -- --baseUrl "https://www.amazon.ca/"`

I just tried this with Amazon US and it worked accordingly (it's the only other amazon account I have content available in so can't test Canada specifically).

Note that I also just pushed up an update to allow for manually logging in using `--manualAuth` if the auto login isn't working for you. Each region seems to have different login flows.

**Comment by usuallymatt** [comment]
That worked for logging in and it appeared to start downloading but I get an error soon after that states:
Error: ENOENT: no such file or directory, open '/home/matt/Downloads/amazon-kindle-bulk-downloader-main/downloads/bookname.azw'

**Comment by treetrum** [comment]
Ok, progress :D 

I think that's just because the download folder didn't exist. I've patched the script to create the download folder now when it needs to. Can you pull and try again. Let me know how you go.
